# Generated by Django 6.0.3 on 2026-03-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='Хранение', max_length=150, verbose_name='Адрес')),
                ('section', models.CharField(max_length=150, verbose_name='Разделы (Отрасль знания)')),
                ('author', models.CharField(blank=True, max_length=200, null=True, verbose_name='Фамилия автора')),
                ('title', models.CharField(max_length=300, verbose_name='Название книги')),
                ('inventory_number', models.CharField(max_length=50, unique=True, verbose_name='Инвентариз. №')),
                ('cipher', models.CharField(blank=True, max_length=100, null=True, verbose_name='Шифр')),
                ('publication_year', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость книг')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['title'],
            },
        ),
    ]
