# Generated by Django 6.0.3 on 2026-05-31 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_section_alter_book_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Адрес / Местонахождение')),
            ],
            options={
                'verbose_name': 'Местонахождение',
                'verbose_name_plural': 'Местонахождения',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.address', verbose_name='Адрес'),
        ),
    ]
