# --- Настройки для Проекта 1 (Книги) ---
server {
    listen 80; # Внутри контейнера слушает 80, наружу смотрит как 8080
    server_name localhost;

    location /static/ {
        alias /var/www/book/static/;
    }

    location / {
        proxy_pass http://web_book:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

# --- Настройки для Проекта 2 (Читатели) ---
server {
    listen 81; # Внутри контейнера слушает 81, наружу смотрит как 8081
    server_name localhost;

    location /static/ {
        alias /var/www/readers/static/;
    }

    location / {
        proxy_pass http://web_readers:8000; # Отправляем во второй контейнер
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}